site_name: Integração Google Sheets + Power BI
theme:
  name: material
  markdown_extensions:
    - codehilite
  palette:
    scheme: slate 
    primary: custom
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Início: index.md
  - Código: codigo.md
  - Padronização: padronizacao.md
  - Power BI: powerbi.md
  - Tratamento PBI: power_query.md
  - Conclusão: conclusao.md
